name: CI/CD Spring Boot and PostgreSQL to AWS EC2 (Docker Hub)

on:
  push:
    branches:
      - main

env:
  JAVA_VERSION: '17'
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_REPOSITORY: 'supplyhub-repo' # Nome do seu repositório no Docker Hub

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Build Spring Boot application with Maven
        run: mvn clean install -DskipTests

      - name: Get JAR file name
        id: get_jar_name
        run: echo "JAR_FILE_NAME=$(find target -name "*.jar" -print -quit | xargs basename)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image to Docker Hub
        env:
          IMAGE_TAG: latest
        run: |
          docker build -t $DOCKER_HUB_USERNAME/$DOCKER_HUB_REPOSITORY:$IMAGE_TAG .
          docker push $DOCKER_HUB_USERNAME/$DOCKER_HUB_REPOSITORY:$IMAGE_TAG

      - name: Deploy to EC2 via SSH (Docker Hub)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Conectado à instância EC2: ${{ secrets.EC2_HOST }}"
            echo "Preparando ambiente Docker..."

            NETWORK_NAME="my-supplyhub-network"
            DB_CONTAINER_NAME="my-postgres-db"
            DB_IMAGE="postgres:13-alpine"
            DB_PASSWORD="${{ secrets.DB_ROOT_PASSWORD }}"
            DB_USER="supplyhub"
            DB_NAME="supplyhubdb"

            APP_CONTAINER_NAME="spring-boot-app-container"
            APP_IMAGE_URI="$DOCKER_HUB_USERNAME/$DOCKER_HUB_REPOSITORY:latest"
            APP_PORT_INTERNAL="8080"
            APP_PORT_HOST="80"

            # --- Operações com a rede Docker ---
            if ! sudo docker network ls | grep -q "$NETWORK_NAME"; then
              echo "Criando rede Docker: $NETWORK_NAME"
              sudo docker network create $NETWORK_NAME
            fi

            # --- Operações com o container do Banco de Dados ---
            echo "Parando e removendo container antigo do banco, se existir..."
            if sudo docker ps -a --filter "name=$DB_CONTAINER_NAME" --format "{{.ID}}" | grep -q .; then
              sudo docker stop $DB_CONTAINER_NAME
              sudo docker rm $DB_CONTAINER_NAME
            fi

            echo "Puxando imagem do PostgreSQL..."
            sudo docker pull $DB_IMAGE

            echo "Rodando novo container do banco..."
            sudo docker run -d \
              --name $DB_CONTAINER_NAME \
              --network $NETWORK_NAME \
              -e POSTGRES_DB=$DB_NAME \
              -e POSTGRES_USER=$DB_USER \
              -e POSTGRES_PASSWORD=$DB_PASSWORD \
              -p 5432:5432 \
              $DB_IMAGE

            echo "Aguardando banco inicializar..."
            sleep 10

            # --- Operações com o container da Aplicação Spring Boot (Docker Hub) ---
            echo "Parando e removendo container antigo da aplicação, se existir..."
            if sudo docker ps -a --filter "name=$APP_CONTAINER_NAME" --format "{{.ID}}" | grep -q .; then
              sudo docker stop $APP_CONTAINER_NAME
              sudo docker rm $APP_CONTAINER_NAME
            fi

            echo "Puxando nova imagem Docker da aplicação Spring Boot do Docker Hub..."
            sudo docker pull $APP_IMAGE_URI

            echo "Subindo nova aplicação com imagem atualizada do Docker Hub..."
            SPRING_DATASOURCE_URL_VALUE="jdbc:postgresql://${DB_CONTAINER_NAME}:5432/${DB_NAME}"

            sudo docker run --pull always -d \
              --name $APP_CONTAINER_NAME \
              --network $NETWORK_NAME \
              -p $APP_PORT_HOST:$APP_PORT_INTERNAL \
              -e SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL_VALUE \
              -e SPRING_DATASOURCE_USERNAME=$DB_USER \
              -e SPRING_DATASOURCE_PASSWORD=$DB_PASSWORD \
            $APP_IMAGE_URI

            echo "Limpeza de imagens Docker não utilizadas..."
            sudo docker system prune -f